name: A-Team
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - ca-certificates=2021.10.26
  - certifi=2021.10.8
  - openssl=1.1.1l
  - pip=21.2.4
  - python=3.8.12
  - setuptools=58.0.4
  - sqlite=3.36.0
  - tk=8.6.11
  - wheel=0.37.0
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - albumentations==1.1.0
    - cycler==0.11.0
    - fonttools==4.28.3
    - imageio==2.13.1
    - joblib==1.1.0
    - kiwisolver==1.3.2
    - matplotlib==3.5.0
    - networkx==2.6.3
    - numpy==1.21.4
    - opencv-python==4.5.4.60
    - opencv-python-headless==4.5.4.60
    - packaging==21.3
    - pandas==1.3.4
    - pillow==8.4.0
    - pyparsing==3.0.6
    - python-dateutil==2.8.2
    - pytz==2021.3
    - pywavelets==1.2.0
    - pyyaml==6.0
    - qudida==0.0.4
    - scikit-image==0.19.0
    - scikit-learn==1.0.1
    - scipy==1.7.3
    - seaborn==0.11.2
    - setuptools-scm==6.3.2
    - six==1.16.0
    - threadpoolctl==3.0.0
    - tifffile==2021.11.2
    - tomli==1.2.2
    - torch==1.10.0
    - torchvision==0.11.1
    - tqdm==4.62.3
    - typing-extensions==4.0.1
